### ISSUE TITLE
The portfolio layout needs attention.

### ISSUE THREAD

**Issue by i-shubhamprakash** [vamsikrishnareddybevara/vamsikrishnareddybevara#2]
I can work on the layout of your portfolio to make it responsive

**Comment by vamsikrishnareddybevara** [comment]
Go ahead and add the feature

**Comment by i-shubhamprakash** [comment]
I have fix the layout issue and gave it an entirely new design. Enjoy...

**Comment by vamsikrishnareddybevara** [comment]
Thanks
